---
# tasks file for nginx

- name: Add the Nginx signing key
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add the Nginx APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://nginx.org/packages/ubuntu jammy nginx
    state: present
  register: nginx_repo_output

- name: Update the APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx 1.26
  ansible.builtin.apt:
    name: nginx=1.26.0-1~jammy
    state: present
  register: install_nginx_output


# This is the file path structure for the recent version of nginx. 1.26 is an older version
# - name: Configure Nginx
#   ansible.builtin.template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/sites-available/default
#   notify: Reload Nginx

# - name: Enable Nginx site
#   ansible.builtin.file:
#     src: /etc/nginx/sites-available/default
#     dest: /etc/nginx/sites-enabled/default
#     state: link
#   notify: Reload Nginx

- name: Remove default Nginx site configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - Restart Nginx   # This must match exactly the way it is named in the handlers

- name: Create new default configuration from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - Restart Nginx   # This must match exactly the way it is named in the handlers
