---
# tasks file for app_deploy\

- name: Create virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/stage_5b/.venv
    creates: /opt/stage_5b/.venv
  become: yes
  become_user: hng
  register: venv_created

- name: Install project dependencies
  ansible.builtin.pip:
    requirements: /opt/stage_5b/requirements.txt
    virtualenv: /opt/stage_5b/.venv
  become: yes
  become_user: hng

- name: Create an env file
  ansible.builtin.template:
    src: env.j2
    dest: /opt/stage_5b/.env
  become: yes
  become_user: hng
  
- name: Start FastAPI application
  ansible.builtin.shell: |
    source /opt/stage_5b/.venv/bin/activate
    nohup uvicorn main:app --host 127.0.0.1 --port 3000 > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &
  args:
    executable: /bin/bash
    chdir: /opt/stage_5b
  become: yes
  become_user: hng
  environment:
    PATH: "/opt/stage_5b/.venv/bin:{{ ansible_env.PATH }}"
  register: api_started

- name: Ensure FastAPI application is running
  wait_for:
    port: 3000
    delay: 5
    timeout: 30
