---
# tasks file for user

- name: Create hng user
  ansible.builtin.user:
    name: "{{ name }}"
    create_home: yes
  register: create_user_output 

- name: Set permissions for hng user's home directory
  ansible.builtin.file:
    path: "{{ home_path }}"
    mode: '0750'
    owner: hng
    group: hng
  become: yes
  register: user_permissions_output 

- name: Add hng user to sudoers
  lineinfile:
    path: "{{ sudoers }}"
    line: "{{ line }}"
    validate: "{{ validate }}"
  register: priviledge_action_output 
    

- name: Create log directory
  file:
    path: "{{ log_path }}"
    state: directory
    owner: hng
    group: hng
    mode: '0755'

- name: Create log files
  file:
    path: "{{ item }}"
    state: touch
    owner: hng
    group: hng
    mode: '0644'
  loop:
    - "{{ log_error_file }}"
    - "{{ log_output_file }}"    

    
