---
# handlers file for nginx

- name: Start and enable Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes


- name: Restart Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
