name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
    - name: Run playbook
      run: |
        ansible-playbook -i hosts.ini playbook.yml
